# all:
#   hosts:
#     elasticsearch:
#       ansible_host: "{{ elasticsearch_ip }}"
#       ansible_user: "ubuntu"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     logstash:
#       ansible_host: "{{ logstash_ip }}"
#       ansible_user: "ubuntu"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
# apache:
#       ansible_host: "{{ apache_ip }}"
#       ansible_user: "ec2-user"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     syslog:
#       ansible_host: "{{ syslog_ip }}"
#       ansible_user: "ec2-user"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     kibana:
#       ansible_host: "{{ kibana_ip }}"
#       ansible_user: "ubuntu"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no'


# all:
#   hosts:
#     elasticsearch:
#       ansible_host: "{{ elasticsearch_ip }}"
#       ansible_user: "ubuntu"
#       #ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i "~/Downloads/Team1KeyPair.pem" -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     logstash:
#       ansible_host: "{{ logstash_ip }}"
#       ansible_user: "ubuntu"
#       #ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i "~/Downloads/Team1KeyPair.pem" -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     apache:
#       ansible_host: "{{ apache_ip }}"
#       ansible_user: "ec2-user"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i "~/Downloads/Team1KeyPair.pem" -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     syslog:
#       ansible_host: "{{ syslog_ip }}"
#       ansible_user: "ec2-user"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i "~/Downloads/Team1KeyPair.pem" -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
#     kibana:
#       ansible_host: "{{ kibana_ip }}"
#       ansible_user: "ubuntu"
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#       ansible_ssh_private_key_file: "~/Downloads/Team1KeyPair.pem"
  
all:
  hosts:
    elasticsearch:
      ansible_host: "{{ elasticsearch_ip }}"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    logstash:
      ansible_host: "{{ logstash_ip }}"
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    apache:
      ansible_host: "{{ apache_ip }}"
      ansible_user: "ec2-user"
      ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    syslog:
      ansible_host: "{{ syslog_ip }}"
      ansible_user: "ec2-user"
      ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    kibana:
      ansible_host: "{{ kibana_ip }}"
      ansible_user: "ubuntu"