all:
  hosts:
    elasticsearch:
      ansible_host: "{{ elasticsearch_ip }}"
      ansible_user: "ubuntu"
      #ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    logstash:
      ansible_host: "{{ logstash_ip }}"
      ansible_user: "ubuntu"
      #ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    apache:
      ansible_host: "{{ apache_ip }}"
      ansible_user: "ec2-user"
      ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    syslog:
      ansible_host: "{{ syslog_ip }}"
      ansible_user: "ec2-user"
      ansible_ssh_private_key_file: ~/.ssh/Team1KeyPair.pem
    kibana:
      ansible_host: "{{ kibana_ip }}"
      ansible_user: "ubuntu"