all:
  hosts:
    elasticsearch:
      ansible_host: "{{ elasticsearch_ip }}"
      ansible_user: "ubuntu"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
    logstash:
      ansible_host: "{{ logstash_ip }}"
      ansible_user: "ubuntu"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q {{ ansible_user }}@{{ bastion_ip }}"'
    kibana:
      ansible_host: "{{ kibana_ip }}"
      ansible_user: "ubuntu"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_private_key_file: "~/Downloads/Team1KeyPair.pem"