name: Ansible Configuration
on:
  push:
    branches:
      - main
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code in the pipeline
        uses: actions/checkout@v2

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts.yml
            --verbose