name: Ansible Configuration

env:
  AWS_ACCESS_KEY_ID       : ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY   : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - main
      - development
      - pipeline
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code in the pipeline
        uses: actions/checkout@v2

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Setting environment variables
        run: |
          echo "AWS_DEFAULT_REGION=eu-west-1" >> $GITHUB_ENV
          echo "AWS_SG_ID=sg-074c0289463cea353" >> $GITHUB_ENV

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/Team1KeyPair.pem
          sudo chmod 600 ~/.ssh/Team1KeyPair.pem
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Fetch IPs and setup ssh.config
        run: |
          chmod +x ./fetch-ips.sh
          ./fetch-ips.sh
        shell: bash

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

      - name: Run Playbooks
        run: ansible-playbook playbook.yml -vvvv

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts.yml
            --verbose
      
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}